databases:
  - name: sponstrdb
    plan: free
    databaseName: sponstr
    user: sponstr

services:
  - type: web
    plan: free
    name: sponstr
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sponstr.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sponstrdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4